services:
  web:
    build: .             
    ports:
      - "80:8000"                     
    environment:
      - DATABASE_URL=${DATABASE_URL}  
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
    command: fastapi run main.py --host 0.0.0.0 --port 8000 
 