FROM python
 
WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

EXPOSE 8000

RUN pip install -r requirements.txt
 
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
