services:
  web:
    build: .             
    ports:
      - "80:8000"        
    depends_on:
      - db               
    environment:
      - DATABASE_URL=${DATABASE_URL}  
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
    command: fastapi run main.py --host 0.0.0.0 --port 8000 
 
  db:
    image: postgres 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  
      POSTGRES_DB: ${POSTGRES_DB} 
    volumes:
      - postgres_data:/var/lib/postgresql/data  

volumes:
  postgres_data:
    driver: local